const getMouseMove = function (coords) {
  return new vmContext.MouseEvent("mousemove", {
    altKey: false,
    bubbles: true,
    button: 0,
    buttons: 0,
    cancelBubble: false,
    cancelable: true,
    clientX: Math.floor(coords.x),
    clientY: Math.floor(coords.y),
    composed: true,
    ctrlKey: false,
    currentTarget: null,
    defaultPrevented: false,
    detail: 0,
    eventPhase: 0,
    fromElement: null,
    isTrusted: true,
    layerX: Math.floor(coords.x),
    layerY: Math.floor(coords.y),
    metaKey: false,
    movementX: Math.floor(coords.x - previousX),
    movementY: Math.floor(coords.y - previousY),
    offsetX: Math.floor(coords.x),
    offsetY: Math.floor(coords.y),
    pageX: Math.floor(coords.x),
    pageY: Math.floor(coords.y),
    path: [
      vmContext.document.querySelector("div.geetest_slider_button"),
      vmContext.document.querySelector("div.geetest_slider.geetest_success"),
      vmContext.document.querySelector("div.geetest_wrap"),
      vmContext.document.querySelector(
        "div.geetest_holder.geetest_mobile.geetest_ant.geetest_embed"
      ),
      vmContext.document.querySelector("div.geetest_fullpage_click_box"),
      vmContext.document.querySelector("div.geetest_fullpage_click_wrap"),
      vmContext.document.querySelector(
        "div.geetest_fullpage_click.geetest_float.geetest_wind.geetest_slide3"
      ),
      vmContext.document.body,
      vmContext.document.querySelector("html"),
      vmContext.document,
      vmContext.window,
    ],
    relatedTarget: null,
    returnValue: true,
    screenX: Math.floor(coords.x),
    screenY: Math.floor(coords.y + 71),
    shiftKey: false,
    sourceCapabilities: { firesTouchEvents: false },
    srcElement: vmContext.document.querySelector("div.geetest_slider_button"),
    target: vmContext.document.querySelector("div.geetest_slider_button"),
    timeStamp: vmContext.performance.now(), // currentTime,
    toElement: vmContext.document.querySelector("div.geetest_slider_button"),
    type: "mousemove",
    view: vmContext.window,
    which: 0,
    x: Math.floor(coords.x),
    y: Math.floor(coords.y),
  });
};

const getPointerMove = function (coords, isClicking) {
  return new vmContext.MouseEvent("pointermove", {
    altKey: false,
    altitudeAngle: 1.5707963267948966,
    azimuthAngle: 0,
    bubbles: true,
    button: -1,
    buttons: isClicking ? 1 : 0,
    cancelBubble: false,
    cancelable: true,
    clientX: coords.x,
    clientY: coords.y,
    composed: true,
    ctrlKey: false,
    currentTarget: null,
    defaultPrevented: isClicking ? true : false,
    detail: 0,
    eventPhase: 0,
    fromElement: null,
    height: 1,
    isPrimary: true,
    isTrusted: true,
    layerX: Math.floor(coords.x),
    layerY: Math.floor(coords.y),
    metaKey: false,
    movementX: Math.floor(coords.x - previousX),
    movementY: Math.floor(coords.y - previousY),
    offsetX: coords.x,
    offsetY: coords.y,
    pageX: coords.x,
    pageY: coords.y,
    path: [
      vmContext.document.querySelector("div.geetest_slider_button"),
      vmContext.document.querySelector("div.geetest_slider.geetest_success"),
      vmContext.document.querySelector("div.geetest_wrap"),
      vmContext.document.querySelector(
        "div.geetest_holder.geetest_mobile.geetest_ant.geetest_embed"
      ),
      vmContext.document.querySelector("div.geetest_fullpage_click_box"),
      vmContext.document.querySelector("div.geetest_fullpage_click_wrap"),
      vmContext.document.querySelector(
        "div.geetest_fullpage_click.geetest_float.geetest_wind.geetest_slide3"
      ),
      vmContext.document.body,
      vmContext.document.querySelector("html"),
      vmContext.document,
      vmContext.window,
    ],
    pointerId: 1,
    pointerType: "mouse",
    pressure: isClicking ? 0.5 : 0,
    relatedTarget: null,
    returnValue: isClicking ? false : true,
    screenX: coords.x,
    screenY: coords.y + 71,
    shiftKey: false,
    sourceCapabilities: null,
    srcElement: vmContext.document.querySelector("div.geetest_slider_button"),
    tangentialPressure: 0,
    target: vmContext.document.querySelector("div.geetest_slider_button"),
    tiltX: 0,
    tiltY: 0,
    timeStamp: vmContext.performance.now(), // currentTime,
    toElement: null,
    twist: 0,
    type: "pointermove",
    view: vmContext.window,
    which: 0,
    width: 1,
    x: coords.x,
    y: coords.y,
  });
};

const getPointerDown = function (coords) {
  return new vmContext.MouseEvent("pointerdown", {
    altKey: false,
    altitudeAngle: 1.5707963267948966,
    azimuthAngle: 0,
    bubbles: true,
    button: 0,
    buttons: 1,
    cancelBubble: false,
    cancelable: true,
    clientX: coords.x,
    clientY: coords.y,
    composed: true,
    ctrlKey: false,
    currentTarget: null,
    defaultPrevented: true,
    detail: 0,
    eventPhase: 0,
    fromElement: null,
    height: 1,
    isPrimary: true,
    isTrusted: true,
    layerX: Math.floor(coords.x),
    layerY: Math.floor(coords.y),
    metaKey: false,
    movementX: Math.floor(coords.x - previousX),
    movementY: Math.floor(coords.y - previousY),
    offsetX: coords.x,
    offsetY: coords.y,
    pageX: coords.x,
    pageY: coords.y,
    path: [
      vmContext.document.querySelector("div.geetest_slider_button"),
      vmContext.document.querySelector("div.geetest_slider.geetest_success"),
      vmContext.document.querySelector("div.geetest_wrap"),
      vmContext.document.querySelector(
        "div.geetest_holder.geetest_mobile.geetest_ant.geetest_embed"
      ),
      vmContext.document.querySelector("div.geetest_fullpage_click_box"),
      vmContext.document.querySelector("div.geetest_fullpage_click_wrap"),
      vmContext.document.querySelector(
        "div.geetest_fullpage_click.geetest_float.geetest_wind.geetest_slide3"
      ),
      vmContext.document.body,
      vmContext.document.querySelector("html"),
      vmContext.document,
      vmContext.window,
    ],
    pointerId: 1,
    pointerType: "mouse",
    pressure: 0.5,
    relatedTarget: null,
    returnValue: false,
    screenX: coords.x,
    screenY: coords.y + 71,
    shiftKey: false,
    sourceCapabilities: null,
    srcElement: vmContext.document.querySelector("div.geetest_slider_button"),
    tangentialPressure: 0,
    target: vmContext.document.querySelector("div.geetest_slider_button"),
    tiltX: 0,
    tiltY: 0,
    timeStamp: vmContext.performance.now(), // currentTime,
    toElement: null,
    twist: 0,
    type: "pointermove",
    view: vmContext.window,
    which: 1,
    width: 1,
    x: coords.x,
    y: coords.y,
  });
};

const getPointerUp = function (coords) {
  return new vmContext.MouseEvent("pointerup", {
    altKey: false,
    altitudeAngle: 1.5707963267948966,
    azimuthAngle: 0,
    bubbles: true,
    button: 0,
    buttons: 0,
    cancelBubble: false,
    cancelable: true,
    clientX: coords.x,
    clientY: coords.y,
    composed: true,
    ctrlKey: false,
    currentTarget: null,
    defaultPrevented: true,
    detail: 0,
    eventPhase: 0,
    fromElement: null,
    height: 1,
    isPrimary: true,
    isTrusted: true,
    layerX: Math.floor(coords.x),
    layerY: Math.floor(coords.y),
    metaKey: false,
    movementX: Math.floor(coords.x - previousX),
    movementY: Math.floor(coords.y - previousY),
    offsetX: coords.x,
    offsetY: coords.y,
    pageX: coords.x,
    pageY: coords.y,
    path: [
      vmContext.document.querySelector("div.geetest_slider_button"),
      vmContext.document.querySelector("div.geetest_slider.geetest_success"),
      vmContext.document.querySelector("div.geetest_wrap"),
      vmContext.document.querySelector(
        "div.geetest_holder.geetest_mobile.geetest_ant.geetest_embed"
      ),
      vmContext.document.querySelector("div.geetest_fullpage_click_box"),
      vmContext.document.querySelector("div.geetest_fullpage_click_wrap"),
      vmContext.document.querySelector(
        "div.geetest_fullpage_click.geetest_float.geetest_wind.geetest_slide3"
      ),
      vmContext.document.body,
      vmContext.document.querySelector("html"),
      vmContext.document,
      vmContext.window,
    ],
    pointerId: 1,
    pointerType: "mouse",
    pressure: 0,
    relatedTarget: null,
    returnValue: false,
    screenX: coords.x,
    screenY: coords.y + 71,
    shiftKey: false,
    sourceCapabilities: null,
    srcElement: vmContext.document.querySelector("div.geetest_slider_button"),
    tangentialPressure: 0,
    target: vmContext.document.querySelector("div.geetest_slider_button"),
    tiltX: 0,
    tiltY: 0,
    timeStamp: vmContext.performance.now(), // currentTime,
    toElement: null,
    twist: 0,
    type: "pointerup",
    view: vmContext.window,
    which: 1,
    width: 1,
    x: coords.x,
    y: coords.y,
  });
};

const getClick = function (coords) {
  return new vmContext.MouseEvent("pointerup", {
    altKey: false,
    bubbles: true,
    button: 0,
    buttons: 0,
    cancelBubble: false,
    cancelable: true,
    clientX: Math.floor(coords.x),
    clientY: Math.floor(coords.y),
    composed: true,
    ctrlKey: false,
    currentTarget: null,
    defaultPrevented: false,
    detail: 1,
    eventPhase: 0,
    fromElement: null,
    isTrusted: true,
    layerX: Math.floor(coords.x),
    layerY: Math.floor(coords.y),
    metaKey: false,
    movementX: Math.floor(coords.x - previousX),
    movementY: Math.floor(coords.y - previousY),
    offsetX: Math.floor(coords.x),
    offsetY: Math.floor(coords.y),
    pageX: coords.x,
    pageY: coords.y,
    path: [
      vmContext.document.querySelector("div.geetest_slider_button"),
      vmContext.document.querySelector("div.geetest_slider.geetest_success"),
      vmContext.document.querySelector("div.geetest_wrap"),
      vmContext.document.querySelector(
        "div.geetest_holder.geetest_mobile.geetest_ant.geetest_embed"
      ),
      vmContext.document.querySelector("div.geetest_fullpage_click_box"),
      vmContext.document.querySelector("div.geetest_fullpage_click_wrap"),
      vmContext.document.querySelector(
        "div.geetest_fullpage_click.geetest_float.geetest_wind.geetest_slide3"
      ),
      vmContext.document.body,
      vmContext.document.querySelector("html"),
      vmContext.document,
      vmContext.window,
    ],
    relatedTarget: null,
    returnValue: true,
    screenX: Math.floor(coords.x),
    screenY: Math.floor(coords.y + 71),
    shiftKey: false,
    sourceCapabilities: { firesTouchEvents: false },
    srcElement: vmContext.document.querySelector("div.geetest_slider_button"),
    target: vmContext.document.querySelector("div.geetest_slider_button"),
    timeStamp: vmContext.performance.now(), // currentTime,
    toElement: vmContext.document.querySelector("div.geetest_slider_button"),
    type: "click",
    view: vmContext.window,
    which: 1,
    x: Math.floor(coords.x),
    y: Math.floor(coords.y),
  });
};

const dispatchSlideEvt = function (event) {
  vmContext.window.dispatchEvent(event);
  vmContext.window.document.dispatchEvent(event);
  elem.dispatchEvent(event);
};

module.exports = {
  getMouseMove,
  getPointerMove,
  getPointerDown,
  getPointerUp,
  getClick,
  dispatchSlideEvt,
};
